name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]
        os: [ ubuntu-latest ]

      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.XX
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'  # 啟用 pip 緩存加速安裝

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -e ".[test]"

      - name: Run tests with coverage
        run: |
          pytest tests/ -m "not requires_data" \
          --cov=AeroViz \
                --cov-report=term-missing \
                --cov-report=xml \
                -v

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.python-version }}-${{ github.sha }}
          path: coverage.xml
          if-no-files-found: error
