name: Delete Version and Releases

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to delete (e.g., v0.1.12)'
        required: true
        type: string

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Delete GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          release_id=$(curl -s -H "Authorization: token ${{ github.token }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ inputs.version }}" \
            | jq -r '.id')
          
          if [ "$release_id" != "null" ]; then
            curl -X DELETE -H "Authorization: token ${{ github.token }}" \
              "https://api.github.com/repos/${{ github.repository }}/releases/$release_id"
            echo "Deleted GitHub release for tag ${{ inputs.version }}"
          else
            echo "No GitHub release found for tag ${{ inputs.version }}"
          fi

      - name: Delete GitHub Tag
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - run: |
          git push origin --delete ${{ inputs.version }} || echo "Tag might be already deleted"
